// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ppx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BackwardResult struct {
	_tab flatbuffers.Table
}

func GetRootAsBackwardResult(buf []byte, offset flatbuffers.UOffsetT) *BackwardResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BackwardResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BackwardResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BackwardResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BackwardResult) GradInput(obj *Tensor) *Tensor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Tensor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func BackwardResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BackwardResultAddGradInput(builder *flatbuffers.Builder, gradInput flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(gradInput), 0)
}
func BackwardResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
