// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ppx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ForwardResult struct {
	_tab flatbuffers.Table
}

func GetRootAsForwardResult(buf []byte, offset flatbuffers.UOffsetT) *ForwardResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ForwardResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ForwardResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ForwardResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ForwardResult) Values(obj *Tensor, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ForwardResult) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ForwardResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ForwardResultAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(values), 0)
}
func ForwardResultStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ForwardResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
