-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local BackwardResult = {} -- the module
local BackwardResult_mt = {} -- the class metatable

function BackwardResult.New()
    local o = {}
    setmetatable(o, {__index = BackwardResult_mt})
    return o
end
function BackwardResult.GetRootAsBackwardResult(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = BackwardResult.New()
    o:Init(buf, n + offset)
    return o
end
function BackwardResult_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function BackwardResult_mt:GradInput()
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Indirect(o + self.view.pos)
        local obj = require('ppx.Tensor').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function BackwardResult.Start(builder) builder:StartObject(1) end
function BackwardResult.AddGradInput(builder, gradInput) builder:PrependUOffsetTRelativeSlot(0, gradInput, 0) end
function BackwardResult.End(builder) return builder:EndObject() end

return BackwardResult -- return the module