-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local BackwardResult = {} -- the module
local BackwardResult_mt = {} -- the class metatable

function BackwardResult.New()
    local o = {}
    setmetatable(o, {__index = BackwardResult_mt})
    return o
end
function BackwardResult.GetRootAsBackwardResult(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = BackwardResult.New()
    o:Init(buf, n + offset)
    return o
end
function BackwardResult_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function BackwardResult_mt:Values(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('ppx.Tensor').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function BackwardResult_mt:ValuesLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function BackwardResult.Start(builder) builder:StartObject(1) end
function BackwardResult.AddValues(builder, values) builder:PrependUOffsetTRelativeSlot(0, values, 0) end
function BackwardResult.StartValuesVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function BackwardResult.End(builder) return builder:EndObject() end

return BackwardResult -- return the module