-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local BatchOperationResult = {} -- the module
local BatchOperationResult_mt = {} -- the class metatable

function BatchOperationResult.New()
    local o = {}
    setmetatable(o, {__index = BatchOperationResult_mt})
    return o
end
function BatchOperationResult.GetRootAsBatchOperationResult(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = BatchOperationResult.New()
    o:Init(buf, n + offset)
    return o
end
function BatchOperationResult_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function BatchOperationResult_mt:Results(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('ppx.Message').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function BatchOperationResult_mt:ResultsLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function BatchOperationResult.Start(builder) builder:StartObject(1) end
function BatchOperationResult.AddResults(builder, results) builder:PrependUOffsetTRelativeSlot(0, results, 0) end
function BatchOperationResult.StartResultsVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function BatchOperationResult.End(builder) return builder:EndObject() end

return BatchOperationResult -- return the module