-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local BatchOperation = {} -- the module
local BatchOperation_mt = {} -- the class metatable

function BatchOperation.New()
    local o = {}
    setmetatable(o, {__index = BatchOperation_mt})
    return o
end
function BatchOperation.GetRootAsBatchOperation(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = BatchOperation.New()
    o:Init(buf, n + offset)
    return o
end
function BatchOperation_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function BatchOperation_mt:Operations(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('ppx.Message').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function BatchOperation_mt:OperationsLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function BatchOperation.Start(builder) builder:StartObject(1) end
function BatchOperation.AddOperations(builder, operations) builder:PrependUOffsetTRelativeSlot(0, operations, 0) end
function BatchOperation.StartOperationsVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function BatchOperation.End(builder) return builder:EndObject() end

return BatchOperation -- return the module