-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local Forward = {} -- the module
local Forward_mt = {} -- the class metatable

function Forward.New()
    local o = {}
    setmetatable(o, {__index = Forward_mt})
    return o
end
function Forward.GetRootAsForward(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Forward.New()
    o:Init(buf, n + offset)
    return o
end
function Forward_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Forward_mt:Name()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Forward_mt:Input()
    local o = self.view:Offset(6)
    if o ~= 0 then
        local x = self.view:Indirect(o + self.view.pos)
        local obj = require('ppx.Tensor').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function Forward.Start(builder) builder:StartObject(2) end
function Forward.AddName(builder, name) builder:PrependUOffsetTRelativeSlot(0, name, 0) end
function Forward.AddInput(builder, input) builder:PrependUOffsetTRelativeSlot(1, input, 0) end
function Forward.End(builder) return builder:EndObject() end

return Forward -- return the module