-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local ForwardResult = {} -- the module
local ForwardResult_mt = {} -- the class metatable

function ForwardResult.New()
    local o = {}
    setmetatable(o, {__index = ForwardResult_mt})
    return o
end
function ForwardResult.GetRootAsForwardResult(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = ForwardResult.New()
    o:Init(buf, n + offset)
    return o
end
function ForwardResult_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function ForwardResult_mt:Output()
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Indirect(o + self.view.pos)
        local obj = require('ppx.Tensor').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function ForwardResult.Start(builder) builder:StartObject(1) end
function ForwardResult.AddOutput(builder, output) builder:PrependUOffsetTRelativeSlot(0, output, 0) end
function ForwardResult.End(builder) return builder:EndObject() end

return ForwardResult -- return the module