<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace ppx;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class BackwardResult extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return BackwardResult
     */
    public static function getRootAsBackwardResult(ByteBuffer $bb)
    {
        $obj = new BackwardResult();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    public static function BackwardResultIdentifier()
    {
        return "PPXF";
    }

    public static function BackwardResultBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::BackwardResultIdentifier());
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return BackwardResult
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getGradInput()
    {
        $obj = new Tensor();
        $o = $this->__offset(4);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startBackwardResult(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return BackwardResult
     */
    public static function createBackwardResult(FlatBufferBuilder $builder, $grad_input)
    {
        $builder->startObject(1);
        self::addGradInput($builder, $grad_input);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addGradInput(FlatBufferBuilder $builder, $gradInput)
    {
        $builder->addOffsetX(0, $gradInput, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endBackwardResult(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
