<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace ppx;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class Forward extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return Forward
     */
    public static function getRootAsForward(ByteBuffer $bb)
    {
        $obj = new Forward();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    public static function ForwardIdentifier()
    {
        return "PPXF";
    }

    public static function ForwardBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::ForwardIdentifier());
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return Forward
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getName()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getInput()
    {
        $obj = new Tensor();
        $o = $this->__offset(6);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startForward(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return Forward
     */
    public static function createForward(FlatBufferBuilder $builder, $name, $input)
    {
        $builder->startObject(2);
        self::addName($builder, $name);
        self::addInput($builder, $input);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatBufferBuilder $builder, $name)
    {
        $builder->addOffsetX(0, $name, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addInput(FlatBufferBuilder $builder, $input)
    {
        $builder->addOffsetX(1, $input, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endForward(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
