<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace ppx;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class ForwardResult extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ForwardResult
     */
    public static function getRootAsForwardResult(ByteBuffer $bb)
    {
        $obj = new ForwardResult();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    public static function ForwardResultIdentifier()
    {
        return "PPXF";
    }

    public static function ForwardResultBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::ForwardResultIdentifier());
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ForwardResult
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getOutput()
    {
        $obj = new Tensor();
        $o = $this->__offset(4);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startForwardResult(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ForwardResult
     */
    public static function createForwardResult(FlatBufferBuilder $builder, $output)
    {
        $builder->startObject(1);
        self::addOutput($builder, $output);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addOutput(FlatBufferBuilder $builder, $output)
    {
        $builder->addOffsetX(0, $output, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endForwardResult(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
