// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ppx
{

using global::System;
using global::FlatBuffers;

public struct BackwardResult : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BackwardResult GetRootAsBackwardResult(ByteBuffer _bb) { return GetRootAsBackwardResult(_bb, new BackwardResult()); }
  public static BackwardResult GetRootAsBackwardResult(ByteBuffer _bb, BackwardResult obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BackwardResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Tensor? GradInput { get { int o = __p.__offset(4); return o != 0 ? (Tensor?)(new Tensor()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<BackwardResult> CreateBackwardResult(FlatBufferBuilder builder,
      Offset<Tensor> grad_inputOffset = default(Offset<Tensor>)) {
    builder.StartObject(1);
    BackwardResult.AddGradInput(builder, grad_inputOffset);
    return BackwardResult.EndBackwardResult(builder);
  }

  public static void StartBackwardResult(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddGradInput(FlatBufferBuilder builder, Offset<Tensor> gradInputOffset) { builder.AddOffset(0, gradInputOffset.Value, 0); }
  public static Offset<BackwardResult> EndBackwardResult(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BackwardResult>(o);
  }
};


}
