// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ppx
{

using global::System;
using global::FlatBuffers;

public struct BatchOperation : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BatchOperation GetRootAsBatchOperation(ByteBuffer _bb) { return GetRootAsBatchOperation(_bb, new BatchOperation()); }
  public static BatchOperation GetRootAsBatchOperation(ByteBuffer _bb, BatchOperation obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BatchOperation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Message? Operations(int j) { int o = __p.__offset(4); return o != 0 ? (Message?)(new Message()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int OperationsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<BatchOperation> CreateBatchOperation(FlatBufferBuilder builder,
      VectorOffset operationsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    BatchOperation.AddOperations(builder, operationsOffset);
    return BatchOperation.EndBatchOperation(builder);
  }

  public static void StartBatchOperation(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddOperations(FlatBufferBuilder builder, VectorOffset operationsOffset) { builder.AddOffset(0, operationsOffset.Value, 0); }
  public static VectorOffset CreateOperationsVector(FlatBufferBuilder builder, Offset<Message>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateOperationsVectorBlock(FlatBufferBuilder builder, Offset<Message>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartOperationsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BatchOperation> EndBatchOperation(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BatchOperation>(o);
  }
};


}
