// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ppx
{

using global::System;
using global::FlatBuffers;

public struct ForwardResult : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ForwardResult GetRootAsForwardResult(ByteBuffer _bb) { return GetRootAsForwardResult(_bb, new ForwardResult()); }
  public static ForwardResult GetRootAsForwardResult(ByteBuffer _bb, ForwardResult obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ForwardResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Tensor? Output { get { int o = __p.__offset(4); return o != 0 ? (Tensor?)(new Tensor()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<ForwardResult> CreateForwardResult(FlatBufferBuilder builder,
      Offset<Tensor> outputOffset = default(Offset<Tensor>)) {
    builder.StartObject(1);
    ForwardResult.AddOutput(builder, outputOffset);
    return ForwardResult.EndForwardResult(builder);
  }

  public static void StartForwardResult(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddOutput(FlatBufferBuilder builder, Offset<Tensor> outputOffset) { builder.AddOffset(0, outputOffset.Value, 0); }
  public static Offset<ForwardResult> EndForwardResult(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ForwardResult>(o);
  }
};


}
