// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ppx
{

using global::System;
using global::FlatBuffers;

public struct ForwardResult : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ForwardResult GetRootAsForwardResult(ByteBuffer _bb) { return GetRootAsForwardResult(_bb, new ForwardResult()); }
  public static ForwardResult GetRootAsForwardResult(ByteBuffer _bb, ForwardResult obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ForwardResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Tensor? Values(int j) { int o = __p.__offset(4); return o != 0 ? (Tensor?)(new Tensor()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ValuesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ForwardResult> CreateForwardResult(FlatBufferBuilder builder,
      VectorOffset valuesOffset = default(VectorOffset)) {
    builder.StartObject(1);
    ForwardResult.AddValues(builder, valuesOffset);
    return ForwardResult.EndForwardResult(builder);
  }

  public static void StartForwardResult(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddValues(FlatBufferBuilder builder, VectorOffset valuesOffset) { builder.AddOffset(0, valuesOffset.Value, 0); }
  public static VectorOffset CreateValuesVector(FlatBufferBuilder builder, Offset<Tensor>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, Offset<Tensor>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartValuesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ForwardResult> EndForwardResult(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ForwardResult>(o);
  }
};


}
