// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ppx
{

using global::System;
using global::FlatBuffers;

public struct Forward : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Forward GetRootAsForward(ByteBuffer _bb) { return GetRootAsForward(_bb, new Forward()); }
  public static Forward GetRootAsForward(ByteBuffer _bb, Forward obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Forward __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public Tensor? Input { get { int o = __p.__offset(6); return o != 0 ? (Tensor?)(new Tensor()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Forward> CreateForward(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      Offset<Tensor> inputOffset = default(Offset<Tensor>)) {
    builder.StartObject(2);
    Forward.AddInput(builder, inputOffset);
    Forward.AddName(builder, nameOffset);
    return Forward.EndForward(builder);
  }

  public static void StartForward(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddInput(FlatBufferBuilder builder, Offset<Tensor> inputOffset) { builder.AddOffset(1, inputOffset.Value, 0); }
  public static Offset<Forward> EndForward(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Forward>(o);
  }
};


}
