# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class Backward(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBackward(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Backward()
        x.Init(buf, n + offset)
        return x

    # Backward
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Backward
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Backward
    def Arguments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Backward
    def ArgumentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def BackwardStart(builder): builder.StartObject(2)
def BackwardAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def BackwardAddArguments(builder, arguments): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(arguments), 0)
def BackwardStartArgumentsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def BackwardEnd(builder): return builder.EndObject()
